spring:
  profiles:
    include: secret

  data:
    rest:
      base-path: /api/data

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      # ddl-auto: none
      naming: 
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    defer-datasource-initialization: true

  datasource:
    url: jdbc:mysql://localhost/BLOG?useSSL=false

  sql:
    init:
      mode: always
      # schema-locations:
      #   - classpath:
      data-locations:
        - classpath:BlogUser-data.sql
